Repository mbcabalos/Komunika, pull requests merged in 2025-03, with the labels that each got.

#45 sign language backend
  backend_python/controllers/__pycache__/sign_transcriber.cpython-311.pyc
  backend_python/controllers/sign_transcriber.py
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/lib/screens/auto_caption_screen/auto_caption_page.dart
  mobile_flutter/lib/screens/home_screen/home_page.dart
  mobile_flutter/lib/screens/sign_transcribe_screen/sign_transcribe_page.dart
  mobile_flutter/lib/services/endpoint.dart
  mobile_flutter/lib/test.dart
  mobile_flutter/linux/flutter/generated_plugin_registrant.cc
  mobile_flutter/linux/flutter/generated_plugins.cmake
  mobile_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  mobile_flutter/pubspec.lock
  mobile_flutter/pubspec.yaml
  mobile_flutter/windows/flutter/generated_plugin_registrant.cc
  mobile_flutter/windows/flutter/generated_plugins.cmake
Labels: enhancement

#46 Added a history UI and Database for STT, Auto caption and Sign Trancriber.
  backend_python/audio_files/output.mp3
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/assets/languages/en.json
  mobile_flutter/assets/languages/fil.json
  mobile_flutter/lib/main.dart
  mobile_flutter/lib/screens/auto_caption_screen/auto_caption_page.dart
  mobile_flutter/lib/screens/bottom_nav_screen/botton_nav_page.dart
  mobile_flutter/lib/screens/home_screen/home_page.dart
  mobile_flutter/lib/screens/navigation_screen/navigation_page.dart
  mobile_flutter/lib/screens/settings_screen/settings_FAQ_page.dart
  mobile_flutter/lib/screens/settings_screen/settings_about_page.dart
  mobile_flutter/lib/screens/settings_screen/settings_page.dart
  mobile_flutter/lib/screens/sign_transcribe_screen/sign_transcribe_page.dart
  mobile_flutter/lib/screens/speech_to_text_screen/stt_page.dart
  mobile_flutter/lib/screens/text_to_speech_screen/tts_page.dart
  mobile_flutter/lib/screens/text_to_speech_screen/voice_message_page.dart
  mobile_flutter/lib/services/repositories/database_helper.dart
  mobile_flutter/lib/utils/colors.dart
  mobile_flutter/lib/widgets/global_widgets/app_bar.dart
  mobile_flutter/lib/widgets/global_widgets/delete_history.dart
  mobile_flutter/lib/widgets/global_widgets/history.dart
  mobile_flutter/lib/widgets/text_to_speech_widgets/tts_card.dart
Labels: enhancement

#47 Implemented flutter to backend sign transcribe(initial)
  backend_python/app.py
  backend_python/controllers/__pycache__/sign_transcriber.cpython-311.pyc
  backend_python/controllers/__pycache__/sign_transcriber.cpython-313.pyc
  backend_python/controllers/__pycache__/text_to_speech.cpython-311.pyc
  backend_python/controllers/__pycache__/text_to_speech.cpython-313.pyc
  backend_python/requirements.txt
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/stt_socket.cpython-311.pyc
  backend_python/sockets/sign_transcribe_socket.py
  mobile_flutter/android/app/src/main/AndroidManifest.xml
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_bloc.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_event.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_state.dart
  mobile_flutter/lib/main.dart
  mobile_flutter/lib/screens/home_screen/home_page.dart
  mobile_flutter/lib/screens/sign_transcribe_screen/sign_transcribe_page.dart
  mobile_flutter/lib/services/endpoint.dart
  mobile_flutter/lib/services/live-service-handler/socket_service.dart
  mobile_flutter/pubspec.lock
Labels: enhancement

#48 Fixed stuttering in camera during sign transcription
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/sign_transcribe_socket.py
  mobile_flutter/lib/bloc/bloc_auto_caption/auto_caption_bloc.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_bloc.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_state.dart
  mobile_flutter/pubspec.lock
  mobile_flutter/pubspec.yaml
Labels: documentation

#49 Implemented displaying text on frontend when transcribing sign language
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/sign_transcribe_socket.py
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_bloc.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_event.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_state.dart
  mobile_flutter/lib/screens/sign_transcribe_screen/sign_transcribe_page.dart
  mobile_flutter/lib/screens/speech_to_text_screen/stt_page.dart
  mobile_flutter/lib/services/endpoint.dart
  mobile_flutter/lib/services/live-service-handler/camera_service.dart
Labels: enhancement

#51 Added a Permission Request of camera, microphone, display over apps a…
  .gitignore
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/lib/bloc/bloc_auto_caption/auto_caption_bloc.dart
  mobile_flutter/lib/bloc/bloc_auto_caption/auto_caption_event.dart
  mobile_flutter/lib/bloc/bloc_home/home_bloc.dart
  mobile_flutter/lib/bloc/bloc_home/home_event.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_bloc.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_event.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_state.dart
  mobile_flutter/lib/bloc/bloc_speech_to_text/speech_to_text_bloc.dart
  mobile_flutter/lib/bloc/bloc_speech_to_text/speech_to_text_event.dart
  mobile_flutter/lib/bloc/bloc_speech_to_text/speech_to_text_state.dart
  mobile_flutter/lib/bloc/bloc_text_to_speech/text_to_speech_bloc.dart
  mobile_flutter/lib/bloc/bloc_text_to_speech/text_to_speech_event.dart
  mobile_flutter/lib/screens/auto_caption_screen/auto_caption_page.dart
  mobile_flutter/lib/screens/bottom_nav_screen/botton_nav_page.dart
  mobile_flutter/lib/screens/home_screen/home_page.dart
  mobile_flutter/lib/screens/sign_transcribe_screen/sign_transcribe_page.dart
  mobile_flutter/lib/screens/speech_to_text_screen/stt_page.dart
  mobile_flutter/lib/screens/text_to_speech_screen/tts_page.dart
  mobile_flutter/lib/screens/text_to_speech_screen/voice_message_page.dart
Labels: enhancement

#53 Fixed foreground service crashing on first use
  mobile_flutter/android/app/src/main/AndroidManifest.xml
  mobile_flutter/android/app/src/main/kotlin/com/example/komunika/ForegroundService.kt
  mobile_flutter/android/app/src/main/kotlin/com/example/komunika/MainActivity.kt
  mobile_flutter/lib/bloc/bloc_auto_caption/auto_caption_bloc.dart
Labels: bug fix

#54 Added a clear function t the text fields and Optimize the UI of main …
  backend_python/audio_files/output.mp3
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/sign_transcribe_socket.py
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/assets/languages/en.json
  mobile_flutter/lib/screens/auto_caption_screen/auto_caption_page.dart
  mobile_flutter/lib/screens/sign_transcribe_screen/sign_transcribe_page.dart
  mobile_flutter/lib/screens/speech_to_text_screen/stt_page.dart
  mobile_flutter/lib/screens/text_to_speech_screen/tts_page.dart
  mobile_flutter/lib/services/endpoint.dart
  mobile_flutter/lib/widgets/global_widgets/history.dart
Labels: documentation

#55 Fix the issue of Sign language and auto caption
  backend_python/audio_files/output.mp3
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/sign_transcribe_socket.py
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/android/app/src/main/kotlin/com/example/komunika/FloatingWindowService.kt
  mobile_flutter/android/app/src/main/res/layout/floating_window_layout.xml
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_bloc.dart
  mobile_flutter/lib/services/live-service-handler/socket_service.dart
Labels: bug fix

#56 Bug issues fix
  backend_python/audio_files/output.mp3
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/sign_transcribe_socket.py
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/lib/screens/auto_caption_screen/auto_caption_page.dart
  mobile_flutter/lib/screens/sign_transcribe_screen/sign_transcribe_page.dart
  mobile_flutter/lib/screens/text_to_speech_screen/voice_message_page.dart
  mobile_flutter/lib/utils/shared_prefs.dart
  mobile_flutter/lib/widgets/global_widgets/history.dart
  mobile_flutter/lib/widgets/text_to_speech_widgets/tts_card.dart
Labels: bug fix

#57 Modified code to use more accurate model
  backend_python/controllers/__pycache__/text_to_speech.cpython-311.pyc
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/stt_socket.cpython-311.pyc
  backend_python/sockets/sign_transcribe_socket.py
  mobile_flutter/android/app/src/main/res/drawable/rounded_background.xml
  mobile_flutter/android/app/src/main/res/drawable/rounded_background_bottom.xml
  mobile_flutter/android/app/src/main/res/drawable/rounded_background_top.xml
  mobile_flutter/lib/services/endpoint.dart
Labels: enhancement

#58 Fixed missing codes and used more accurate model
  backend_python/app.py
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/sign_transcribe_socket.py
  backend_python/sockets/test.py
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_bloc.dart
  mobile_flutter/lib/services/live-service-handler/socket_service.dart
Labels: enhancement

#59 Fixed lifecycle of Auto Caption Page
  backend_python/app.py
  backend_python/controllers/__pycache__/text_to_speech.cpython-311.pyc
  backend_python/requirements.txt
  backend_python/sockets/__pycache__/audio_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/stt_socket.cpython-311.pyc
  backend_python/sockets/audio_socket.py
  backend_python/temp_audio.wav
  mobile_flutter/android/app/src/main/kotlin/com/example/komunika/FloatingWindowService.kt
  mobile_flutter/android/app/src/main/kotlin/com/example/komunika/MainActivity.kt
  mobile_flutter/android/app/src/main/res/drawable/rounded_background.xml
  mobile_flutter/android/app/src/main/res/layout/floating_window_layout.xml
  mobile_flutter/lib/bloc/bloc_auto_caption/auto_caption_bloc.dart
  mobile_flutter/lib/main.dart
  mobile_flutter/lib/screens/auto_caption_screen/auto_caption_page.dart
  mobile_flutter/lib/screens/home_screen/home_page.dart
  mobile_flutter/lib/services/endpoint.dart
  mobile_flutter/pubspec.lock
Labels: enhancement, bug fix

#61 Implemented real time audio for STT
  .gitignore
  backend_python/controllers/__pycache__/text_to_speech.cpython-311.pyc
  backend_python/sockets/__pycache__/audio_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/audio_socket.py
  backend_python/temp_audio.wav
  mobile_flutter/.gitignore
  mobile_flutter/lib/bloc/bloc_speech_to_text/speech_to_text_bloc.dart
  mobile_flutter/lib/bloc/bloc_speech_to_text/speech_to_text_event.dart
  mobile_flutter/lib/bloc/bloc_speech_to_text/speech_to_text_state.dart
  mobile_flutter/lib/screens/speech_to_text_screen/stt_page.dart
  mobile_flutter/lib/services/endpoint.dart
  mobile_flutter/lib/services/live-service-handler/socket_service.dart
Labels: enhancement

#62 Benedict
  .gitignore
  backend_python/controllers/__pycache__/text_to_speech.cpython-311.pyc
  backend_python/sockets/__pycache__/audio_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/temp_cleaned_audio.wav
  mobile_flutter/lib/screens/sign_transcribe_screen/sign_transcribe_page.dart
  mobile_flutter/lib/screens/speech_to_text_screen/stt_page.dart
  mobile_flutter/lib/services/endpoint.dart
Labels: enhancement

#63 Fixed state handling for STT page
  mobile_flutter/lib/bloc/bloc_speech_to_text/speech_to_text_bloc.dart
  mobile_flutter/lib/bloc/bloc_speech_to_text/speech_to_text_event.dart
  mobile_flutter/lib/screens/speech_to_text_screen/stt_page.dart
Labels: bug fix

#64 Replace the TTS backend into FLutter TTS Package
  backend_python/audio_files/output.mp3
  backend_python/sockets/__pycache__/audio_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/lib/bloc/bloc_text_to_speech/text_to_speech_bloc.dart
  mobile_flutter/lib/bloc/bloc_text_to_speech/text_to_speech_event.dart
  mobile_flutter/lib/screens/text_to_speech_screen/tts_page.dart
  mobile_flutter/lib/utils/shared_prefs.dart
  mobile_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  mobile_flutter/pubspec.lock
  mobile_flutter/pubspec.yaml
  mobile_flutter/windows/flutter/generated_plugin_registrant.cc
  mobile_flutter/windows/flutter/generated_plugins.cmake
Labels: enhancement

#65 Added some TIPS in home page
  backend_python/audio_files/output.mp3
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/assets/languages/en.json
  mobile_flutter/assets/languages/fil.json
  mobile_flutter/lib/screens/home_screen/home_page.dart
Labels: enhancement

#67 Enahaancements
  backend_python/controllers/__pycache__/text_to_speech.cpython-311.pyc
  backend_python/sockets/sign_transcribe_socket.py
  mobile_flutter/android/app/src/main/kotlin/com/example/komunika/FloatingWindowService.kt
  mobile_flutter/android/app/src/main/res/layout/floating_window_layout.xml
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_bloc.dart
  mobile_flutter/lib/bloc/externals/image_processing.dart
  mobile_flutter/lib/services/endpoint.dart
  mobile_flutter/linux/flutter/generated_plugin_registrant.cc
  mobile_flutter/linux/flutter/generated_plugins.cmake
  mobile_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  mobile_flutter/pubspec.lock
  mobile_flutter/pubspec.yaml
  mobile_flutter/windows/flutter/generated_plugin_registrant.cc
  mobile_flutter/windows/flutter/generated_plugins.cmake
Labels: enhancement

#68 Updated the TTS, Sign Transcribe and remove the __pycache__
  .gitignore
  backend_python/app.py
  backend_python/controllers/__pycache__/sign_transcriber.cpython-311.pyc
  backend_python/controllers/__pycache__/sign_transcriber.cpython-313.pyc
  backend_python/controllers/__pycache__/text_to_speech.cpython-311.pyc
  backend_python/controllers/__pycache__/text_to_speech.cpython-313.pyc
  backend_python/controllers/test.py
  backend_python/models/model_instruction.txt
  backend_python/requirements.txt
  backend_python/sockets/__pycache__/audio_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/sign_transcribe_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/sign_transcriber.cpython-313.pyc
  backend_python/sockets/__pycache__/stt_socket.cpython-311.pyc
  backend_python/sockets/__pycache__/stt_socket.cpython-313.pyc
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/assets/audio/Start.mp3
  mobile_flutter/lib/bloc/bloc_home/home_bloc.dart
  mobile_flutter/lib/bloc/bloc_sign_transcriber/sign_transcriber_bloc.dart
  mobile_flutter/lib/models/sign_language_model.dart
  mobile_flutter/lib/screens/home_screen/home_page.dart
  mobile_flutter/lib/screens/sign_transcribe_screen/gesture.dart
  mobile_flutter/lib/screens/text_to_speech_screen/tts_page.dart
  mobile_flutter/lib/services/endpoint.dart
  mobile_flutter/lib/services/live-service-handler/socket_service.dart
  mobile_flutter/lib/services/repositories/database_helper.dart
  mobile_flutter/lib/utils/image_processing.dart
  mobile_flutter/lib/widgets/global_widgets/history.dart
  mobile_flutter/linux/flutter/generated_plugin_registrant.cc
  mobile_flutter/linux/flutter/generated_plugins.cmake
  mobile_flutter/macos/Flutter/GeneratedPluginRegistrant.swift
  mobile_flutter/pubspec.lock
  mobile_flutter/pubspec.yaml
  mobile_flutter/windows/flutter/generated_plugin_registrant.cc
  mobile_flutter/windows/flutter/generated_plugins.cmake
Labels: enhancement

#70 fix some error
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/arm64-v8a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/armeabi-v7a/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86/configure_fingerprint.bin
  mobile_flutter/android/app/.cxx/Debug/3i3s7035/x86_64/configure_fingerprint.bin
  mobile_flutter/lib/bloc/bloc_home/home_bloc.dart
  mobile_flutter/lib/screens/text_to_speech_screen/tts_page.dart
  mobile_flutter/lib/services/endpoint.dart
Labels: enhancement
